controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

calcul:
    path: '/calcul/{number}'
    controller: App\Controller\MainController::indexter

hello :
    path: 'hello/{prenom}'
    controller : App\Controller\FormController::hello
    defaults:
        prenom : "Bryan"

tuteurs :
    path: '/tuteurs'
    controller : App\Controller\FormController::listes
    